name: 'validate-windows-binary'
description: 'Linux Windows Conda or Wheel Validation'
inputs:
  gpu_arch_type:
    description: 'GPU arch type'
    required: true
    default: 'cpu'
  gpu_arch_ver:
    description: 'GPU arch version'
    required: true
    default: 'cpu'
  installation:
    description: 'Installation instructions'
    required: true
    default: ''
  python_version:
    description: 'Python version'
    required: true
    default: '3.9'
runs:
  using: "composite"
  steps:
    - name: Check nvidia smi
      if: ${{ inputs.gpu_arch_type == 'cuda' }}
      shell: bash
      run: |
        nvidia-smi
    - name: Install conda
      if: ${{ inputs.gpu_arch_type == 'cpu' }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ inputs.python_version }}
        auto-update-conda: true
        miniconda-version: "latest"
        activate-environment: conda-env-${{ github.run_id }}
    - name: Conda Install pytorch and smoke test
      shell: powershell
      env:
        GPU_ARCH_VER: ${{ inputs.gpu_arch_ver }}
        GPU_ARCH_TYPE: ${{ inputs.gpu_arch_type }}
        CUDA_VER: ${{ inputs.desired_cuda }}
      run: |
        conda install numpy pillow python=${{ inputs.python_version }}
        $install = '${{ inputs.installation }}'
        Invoke-Expression $install
        python  ./test/smoke_test/smoke_test.py
