name: Update quick start module
on:
  workflow_dispatch:
    inputs:
      channel:
        description: "Channel to use (nightly, test, release)"
        required: true
        type: choice
        options:
          - release
          - nightly
          - test
      version:
        description: "Version to update"
        required: false
        type: string

jobs:
  validate-binaries:
    uses: pytorch/builder/.github/workflows/validate-binaries.yml@main
    with:
      os: all
      channel: ${{ inputs.channel }}
  linux-matrix:
    needs: [validate-binaries]
    uses: pytorch/test-infra/.github/workflows/generate_binary_build_matrix.yml@main
    with:
      package-type: all
      os: linux
      channel: ${{ inputs.channel }}
  windows-matrix:
    needs: [validate-binaries]
    uses: pytorch/test-infra/.github/workflows/generate_binary_build_matrix.yml@main
    with:
      package-type: all
      os: windows
      channel: ${{ inputs.channel }}
  macos-matrix:
    needs: [validate-binaries]
    uses: pytorch/test-infra/.github/workflows/generate_binary_build_matrix.yml@main
    with:
      package-type: all
      os: macos
      channel: ${{ inputs.channel }}

  generate-json-file:
    needs: [linux-matrix, windows-matrix, macos-matrix]
    runs-on: "ubuntu-18.04"
    steps:
      - name: Checkout builder
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Create json file
        shell: bash
        env:
          LINUX_MATRIX: ${{ needs.linux-matrix.outputs.matrix }}
          WINDOWS_MATRIX: ${{ needs.windows-matrix.outputs.matrix }}
          MACOS_MATRIX: ${{ needs.macos-matrix.outputs.matrix }}
          VERSION: ${{ inputs.version }}
        run: |
          set -ex
          printf '%s\n' "$LINUX_MATRIX" > linux_matrix.json
          printf '%s\n' "$WINDOWS_MATRIX" > windows_matrix.json
          printf '%s\n' "$MACOS_MATRIX" > macos_matrix.json
          if [ -z "${VERSION}" ]; then
                python3 ./scripts/gen_quick_start_module.py --autogenerate enable
          else
                python3 ./scripts/gen_quick_start_module.py --autogenerate enable --version "${VERSION}"
          fi

          rm *_matrix.json
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Modify published_versions.json file
          title: '[Getting Started Page] Modify published_versions.json file'
          body: >
            This PR is auto-generated Gettins Started page update
          labels: automated pr
