name: Update quick start module
on:
  workflow_dispatch:
    inputs:
      channel:
        description: "Channel to use (nightly, test, release)"
        required: true
        type: choice
        options:
          - release
          - nightly
          - test
      version:
        description: "Version to update"
        required: false
        type: string

jobs:
  linux-nightly-matrix:
    uses: pytorch/test-infra/.github/workflows/generate_binary_build_matrix.yml@main
    with:
      package-type: all
      os: linux
      channel: "nightly"
  windows-nightly-matrix:
    uses: pytorch/test-infra/.github/workflows/generate_binary_build_matrix.yml@main
    with:
      package-type: all
      os: windows
      channel: "nightly"
  macos-nightly-matrix:
    uses: pytorch/test-infra/.github/workflows/generate_binary_build_matrix.yml@main
    with:
      package-type: all
      os: macos
      channel: "nightly"
  linux-release-matrix:
    needs: [linux-nightly-matrix]
    uses: pytorch/test-infra/.github/workflows/generate_binary_build_matrix.yml@main
    with:
      package-type: all
      os: linux
      channel: "release"
  windows-release-matrix:
    needs: [windows-nightly-matrix]
    uses: pytorch/test-infra/.github/workflows/generate_binary_build_matrix.yml@main
    with:
      package-type: all
      os: windows
      channel: "release"
  macos-release-matrix:
    needs: [macos-nightly-matrix]
    uses: pytorch/test-infra/.github/workflows/generate_binary_build_matrix.yml@main
    with:
      package-type: all
      os: macos
      channel: "release"

  generate-json-file:
    needs: [linux-nightly-matrix, windows-nightly-matrix, macos-nightly-matrix,
      linux-release-matrix, windows-release-matrix, macos-release-matrix]
    runs-on: "ubuntu-18.04"
    steps:
      - name: Checkout builder
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Create json file
        shell: bash
        env:
          LINUX_NIGHTLY_MATRIX: ${{ needs.linux-nightly-matrix.outputs.matrix }}
          WINDOWS_NIGHTLY_MATRIX: ${{ needs.windows-nightly-matrix.outputs.matrix }}
          MACOS_NIGHTLY_MATRIX: ${{ needs.macos-nightly-matrix.outputs.matrix }}
          LINUX_RELEASE_MATRIX: ${{ needs.linux-release-matrix.outputs.matrix }}
          WINDOWS_RELEASE_MATRIX: ${{ needs.windows-release-matrix.outputs.matrix }}
          MACOS_RELEASE_MATRIX: ${{ needs.macos-release-matrix.outputs.matrix }}
        run: |
          set -ex
          printf '%s\n' "$LINUX_NIGHTLY_MATRIX" > linux_nightly_matrix.json
          printf '%s\n' "$WINDOWS_NIGHTLY_MATRIX" > windows_nightly_matrix.json
          printf '%s\n' "$MACOS_NIGHTLY_MATRIX" > macos_nightly_matrix.json
          printf '%s\n' "$LINUX_RELEASE_MATRIX" > linux_release_matrix.json
          printf '%s\n' "$WINDOWS_RELEASE_MATRIX" > windows_release_matrix.json
          printf '%s\n' "$MACOS_RELEASE_MATRIX" > macos_release_matrix.json
          python3 ./scripts/gen_quick_start_module.py --autogenerate enable
          rm *_matrix.json
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Modify published_versions.json file
          title: '[Getting Started Page] Modify published_versions.json file'
          body: >
            This PR is auto-generated Gettins Started page update
          labels: automated pr
