name: Validate binary  images

on:
  push:
    branches:
      main
    paths:
      - .github/workflows/validate-linux-binaries.yml
  pull_request:
    paths:
      - .github/workflows/validate-linux-binaries.yml

env:
  DOCKER_REGISTRY: "docker.io"
  DOCKER_BUILDKIT: 1
  DOCKER_ID: ${{ secrets.DOCKER_ID }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  WITH_PUSH: ${{ github.event_name == 'push' }}

jobs:
  validate-linux-binaries:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cuda_version: ["11.7", "11.6",  "11.3", "10.2"]
    env:
      GPU_ARCH_TYPE: cuda
      GPU_ARCH_VERSION: ${{ matrix.cuda_version }}
    steps:
      - name: Checkout PyTorch builder
        uses: actions/checkout@v2
      - name: Install conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          auto-update-conda: true
          miniconda-version: "latest"
          activate-environment: testenv
      - name: Test conda install pytorch pre 11.6
        if: ${{ matrix.cuda_version < 11.6 }}
        run: |
            conda install pytorch torchvision torchaudio cudatoolkit=${{ matrix.cuda_version }} -c pytorch-nightly
       - name: Test conda install pytorch 11.6, 11.7
        if: ${{ matrix.cuda_version >= 11.6 }}
        run: |
            conda install pytorch torchvision torchaudio pytorch-cuda=${{ matrix.cuda_version }} -c pytorch-nightly
