name: Validate linux binaries

on:
  workflow_call:
    inputs:
      channel:
        description: "Channel to use (nightly, test, release, all)"
        required: true
        type: string
      ref:
        description: 'Reference to checkout, defaults to empty'
        default: ""
        required: false
        type: string
  workflow_dispatch:
    inputs:
      channel:
        description: "Channel to use (nightly, test, release, all)"
        required: true
        type: choice
        options:
          - release
          - nightly
          - test
          - all
      ref:
        description: 'Reference to checkout, defaults to empty'
        default: ""
        required: false
        type: string

jobs:
  generate-linux-matrix:
    uses: pytorch/test-infra/.github/workflows/generate_binary_build_matrix.yml@main
    with:
      package-type: all
      os: linux
      channel: ${{ inputs.channel }}

  linux:
    needs: generate-linux-matrix
    strategy:
      matrix: ${{ fromJson(needs.generate-linux-matrix.outputs.matrix) }}
      fail-fast: false
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    name: ${{ matrix.build_name }}
    with:
      runner: ${{ matrix.validation_runner }}
      repository: "pytorch/builder"
      ref: ${{ inputs.ref || github.ref }}
      job-name: ${{ matrix.build_name }}
      script: |
        set -ex
        export ENV_NAME="conda-env-${{ github.run_id }}"
        export GPU_ARCH_VER="${{ matrix.gpu_arch_version }}"
        export GPU_ARCH_TYPE="${{ matrix.gpu_arch_type }}"
        export INSTALLATION="${{ matrix.installation }}"
        export CUDA_VER="${{ matrix.desired_cuda }}"
        export DESIRED_PYTHON="${{ matrix.python_version }}"
        export DESIRED_CUDA="${{ matrix.desired_cuda }}"
        export DESIRED_DEVTOOLSET="${{ matrix.dev_toolset }}"
        export PACKAGE_TYPE="${{ matrix.package_type }}"
        export TARGET_OS="linux"

        if [[ ${{ matrix.package_type }} == "libtorch" ]]; then
          curl ${{ matrix.installation }} -o libtorch.zip
          unzip libtorch.zip
        else
          conda create -y -n ${ENV_NAME} python=${{ matrix.python_version }} numpy pillow
          conda activate ${ENV_NAME}
          eval $INSTALLATION
          export CONDA_LIBRARY_PATH="$(dirname $(which python))/../lib"
          export LD_LIBRARY_PATH=$CONDA_LIBRARY_PATH:$LD_LIBRARY_PATH

          python --version
          python  ./test/smoke_test/smoke_test.py

          ${PWD}/check_binary.sh
        fi
