# Scheduled validation of the release binaries
name: cron

on:
  schedule:
    # At 3 am UTC (7 am PDT)
    - cron: "0 3 * * *"
  # Have the ability to trigger this job manually through the API
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/validate-release-binaries.yml
      - .github/workflows/validate-linux-binaries.yml
      - .github/workflows/validate-windows-binaries.yml
      - .github/workflows/validate-macos-binaries.yml
      - .github/workflows/validate-macos-arm64-binaries.yml
      - test/smoke_test/*

jobs:
  release:
    uses: ./.github/workflows/validate-binaries.yml
    with:
      channel: nightly
      os: all
