name: Validate binary  images

on:
  push:
    branches:
      main
    paths:
      - .github/workflows/validate-linux-binaries.yml
  pull_request:
    paths:
      - .github/workflows/validate-linux-binaries.yml

env:
  DOCKER_REGISTRY: "docker.io"
  DOCKER_BUILDKIT: 1
  DOCKER_ID: ${{ secrets.DOCKER_ID }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  WITH_PUSH: ${{ github.event_name == 'push' }}

jobs:
  validate-linux-binaries:
    runs-on: ubuntu-20.04-m60
    strategy:
      matrix:
        cuda_version: ["11.7"]
        python_version: ["3.8"]
    env:
      GPU_ARCH_TYPE: cuda
      GPU_ARCH_VERSION: ${{ matrix.cuda_version }}
      PYTHON_VERSION: ${{ matrix.python_version }}
    steps:
      - name: Checkout PyTorch builder
        uses: actions/checkout@v2
      - name: Install conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python_version }}
          auto-update-conda: true
          miniconda-version: "latest"
          activate-environment: testenv
      - name: Check nvidia smi
        run: |
          nvidia-smi
      - name: Conda Install pytorch and smoke test
        env:
          ENV_NAME: conda-env-${{ github.run_id }}
          CUDA_VER: ${{ matrix.cuda_version }}
        run: |
          set -ex
          conda create -yp ${ENV_NAME} python=${PYTHON_VERSION} numpy
          # if [[ $CUDA_VER == "11.6" || $CUDA_VER == "11.7"  ]]; than
          conda install -p ${ENV_NAME} ffmpeg
          conda install -p ${ENV_NAME} pytorch torchvision torchaudio cudatoolkit=${{ matrix.cuda_version }} -c pytorch -c conda-forge
          # conda install -p ${ENV_NAME}  pytorch pytorch-cuda=${{ matrix.cuda_version }} -c pytorch-nightly -c nvidia
          # else
          #  conda install pytorch torchvision torchaudio cudatoolkit=${{ matrix.cuda_version }} -c pytorch-nightly
          #fi
          # Test torch is importable, by changing cwd and running import commands
          # conda run --cwd /tmp -p ${ENV_NAME} python3 -c "import torch;y=torch.randn([3,5]).cuda();print(y);print(torch.backends.cudnn.version())"
          conda run -p ${ENV_NAME} python3  ./test/smoke_test/smoke_test.py
          conda env remove -p ${ENV_NAME}
