name: Validate binary  images

on:
  push:
    branches:
      main
    paths:
      - .github/workflows/validate-linux-binaries.yml
  pull_request:
    paths:
      - .github/workflows/validate-linux-binaries.yml

jobs:
  generate-matrix:
    uses: pytorch/test-infra/.github/workflows/generate_binary_build_matrix.yml@main
    with:
      package-type: conda
      os: linux
  validate-linux-binaries-conda:
    needs: generate-matrix
    strategy:
      matrix:
        ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    runs-on: ${{ matrix.validation_runner }}
    steps:
      - name: Checkout PyTorch builder
        uses: actions/checkout@v2
      - name: Install conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python_version }}
          auto-update-conda: true
          miniconda-version: "latest"
          activate-environment: testenv
      - name: Check nvidia smi
        if: ${{ matrix.gpu_arch_type == 'cuda' }}
        run: |
          nvidia-smi
      - name: Conda Install pytorch and smoke test
        env:
          ENV_NAME: conda-env-${{ github.run_id }}
          CUDA_VER: ${{ matrix.cuda_version }}
        run: |
          set -ex
          conda create -yp ${ENV_NAME} python=${{ matrix.python_version }} numpy
          case $CUDA_VER in
           ("cpu") {
             conda install -p ${ENV_NAME} pytorch torchvision torchaudio  -c pytorch-nightly;
           }
           ;;
           ("10.2" | "11.3") {
             conda install -p ${ENV_NAME} pytorch torchvision torchaudio cudatoolkit=${CUDA_VER} -c pytorch-nightly;
            }
            ;;
            ("11.6" | "11.7") {
              conda install -p ${ENV_NAME} pytorch torchvision torchaudio cudatoolkit=${CUDA_VER} -c pytorch-nightly -c nvidia;
            }
            ;;
           (*) echo "No binary available"
            ;;
            esac

          conda run -p ${ENV_NAME} python3  ./test/smoke_test/smoke_test.py
          ./check_binary.sh
          conda env remove -p ${ENV_NAME}
